// TikTok Login Kit + Display API — lets a creator connect their TikTok account
// once so we can auto-fetch view_count for their videos instead of an operator
// typing it in by hand. See docs: developers.tiktok.com/doc/login-kit-web.

const CLIENT_KEY = process.env.TIKTOK_CLIENT_KEY;
const CLIENT_SECRET = process.env.TIKTOK_CLIENT_SECRET;
const REDIRECT_URI = process.env.TIKTOK_REDIRECT_URI;

export const tiktokEnabled = !!(CLIENT_KEY && CLIENT_SECRET && REDIRECT_URI);

/** The URL to send a creator to so they can authorize our app. `state` is a CSRF token generated by the caller. */
export function tiktokAuthorizeUrl(state) {
  const params = new URLSearchParams({
    client_key: CLIENT_KEY,
    scope: 'user.info.basic,video.list',
    response_type: 'code',
    redirect_uri: REDIRECT_URI,
    state,
    // Always show the consent screen, even if this account already authorized
    // us before — otherwise TikTok silently skips straight to the redirect on
    // a returning session, which reads as broken (and hides what's granted).
    disable_auto_auth: '1',
  });
  return `https://www.tiktok.com/v2/auth/authorize/?${params.toString()}`;
}

async function tokenRequest(body) {
  const res = await fetch('https://open.tiktokapis.com/v2/oauth/token/', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' },
    body: new URLSearchParams({ client_key: CLIENT_KEY, client_secret: CLIENT_SECRET, ...body }),
    signal: AbortSignal.timeout(10000),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.error) {
    throw new Error(`TikTok token error: ${data.error_description || data.error || res.status}`);
  }
  return data;
}

/** Authorization-code → tokens (called once, right after the redirect back from TikTok). */
export async function exchangeTikTokCode(code) {
  return tokenRequest({ code, grant_type: 'authorization_code', redirect_uri: REDIRECT_URI });
}

/** refresh_token → a fresh access_token (called before syncing if the old one's expired). */
export async function refreshTikTokToken(refreshToken) {
  return tokenRequest({ refresh_token: refreshToken, grant_type: 'refresh_token' });
}

/** Display name for the connected account, shown in the creator dashboard. */
export async function fetchTikTokUserInfo(accessToken) {
  const res = await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name', {
    headers: { Authorization: `Bearer ${accessToken}` },
    signal: AbortSignal.timeout(10000),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`TikTok user.info error: ${res.status}`);
  return data?.data?.user || null;
}

/**
 * All of a creator's videos with view_count, paginated. Capped at 5 pages
 * (≤ 100 videos) — enough for any active creator, and a safety net against a
 * runaway loop if TikTok's `has_more`/`cursor` ever misbehaves.
 */
export async function fetchTikTokVideoViews(accessToken) {
  const videos = [];
  let cursor = 0;
  for (let page = 0; page < 5; page += 1) {
    const res = await fetch('https://open.tiktokapis.com/v2/video/list/?fields=id,view_count', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ cursor, max_count: 20 }),
      signal: AbortSignal.timeout(10000),
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(`TikTok video.list error: ${res.status}`);
    const list = data?.data?.videos || [];
    videos.push(...list);
    if (!data?.data?.has_more || !list.length) break;
    cursor = data.data.cursor;
  }
  return videos; // [{ id, view_count }, ...]
}

/** Extracts the numeric video id from a standard TikTok video URL, or null. */
export function parseTikTokVideoId(url) {
  const m = String(url || '').match(/\/video\/(\d+)/);
  return m ? m[1] : null;
}

/**
 * Is TikTok actually feeding us this creator's views?
 *
 * MIRRORS the WHERE clause of listCreatorsWithTikTok() in db.js:
 *   tiktok_access_token IS NOT NULL AND tiktok_refresh_expires_at > NOW()
 * Change one, change the other. The pair matters because the creator cabinet
 * stops asking for daily screenshots when this is true: if it ever says yes for
 * someone the sync skips, that creator sends nothing, we collect nothing, and
 * the hole only surfaces when they come asking to be paid.
 *
 * Note this is stricter than "has connected": an access token alone is not
 * enough, since the sync gives up once the refresh token lapses.
 */
export function tiktokSyncing(creator) {
  if (!creator?.tiktok_access_token || !creator.tiktok_refresh_expires_at) return false;
  const until = new Date(creator.tiktok_refresh_expires_at).getTime();
  return Number.isFinite(until) && until > Date.now();
}
